### PR TITLE
Apache mesos

### PR DESCRIPTION
**Pull request by moszutij**
New technology content for consideration:
* apache-aurora
* apache-mesos
* chronos

### CODE REVIEW

**Comment by moszutij** [comment]
Pete, 

I was having problems adding the following to apache-mesos.md

tech-relationships: [[add ons, Marathon, Chronos, Aurora][uses, Zookeeper]]

The above item was breaking the formatting. Would be grateful if you could take a look. I suspect it may be because the item references non-existing documents.

Jeff

**Comment by Peter-ODE** [comment]
Jeff,

It looks like you're missing a comma between the two inside lists, i.e. this should be:

[[add ons, Marathon, Chronos, Aurora] , [uses, Zookeeper]]

Can you also have a look at merging the latest master branch into yours - there are a couple of tweaks I made to your Cassandra commit that this pull request is looking to revert.

I'll try and give these a review today or tomorrow, and we'll look at getting them live next week.

Peter

**Comment by moszutij** [comment]
Pete,

Was starring at this for ages. Good to get a fresh pair of eyes. I've made the correction and re-added the  tech relationships. The Apache Cassandra entry has now been realigned with yours. Also spotted and corrected a broken link in the 'Thoughts on NoSQL Wide Column Stores' post. 

Jeff

**Comment by Peter-ODE** [comment]
Jeff,

I’ve had a quick look through and I think they’re all good to go.  If you’re happy, I’ll put these live over the next week.

Do you have any thoughts on Mesos (and more generally cluster management software) for a post on Friday?  I’m going to spend some time next week looking at this area as well so am happy to do this / supplement anything you have.

Many thanks for the contribution,

Peter

**Comment by moszutij** [comment]
Peter,

Happy to have the contributions published over next week. 

In the context of data processing, I'm impressed with the way Mesosphere has taken Mesos and its relatively simple (but groundbreaking) two-level scheduling approach and turned it into a complete platform for running workloads from different cluster computing frameworks. As the core of Mesosphere's DC/OS platform, what's going to be interesting is how Mesos completes in the open source community space with Kubernetes. 

Closely related to Mesos and Kubernetes is containerisation. Some more digging around is required to understand the challenges of adopting this technology for general distributed data processing use cases since persisting data after processing it is hard in an containerised environment. 

Just give me a shout if you have any questions.

Jeff

**Pull request closed without merging**
